"""Deterministic synthetic feature+label generator.

Real annotated video is not available yet (Prompt A's sample dataset ships
placeholder video bytes, not real 1A footage -- see
`ml/scripts/generate_sample_dataset.py`). Prompt C nonetheless requires a
"modest and reproducible baseline" with a concrete, checkable training run
today. This module generates fully synthetic `TrainingSample`s -- clearly
labelled as such everywhere they appear (checkpoint metadata, CLI output,
docs) -- so `events/train.py`'s training loop, splitting, checkpointing, and
every metric in `events/metrics.py` are exercised and testable now. Nothing
in this module is presented as measured real-world model accuracy; swapping
in real `perception` artifacts + `dataset` ground truth (identical
`TrainingSample` shape) is the only change needed once real footage exists.

Uses a small xorshift-style PRNG (matching `adapters_mock._stable_seed`'s
pattern) rather than `random`/`numpy.random` so results never depend on
process-wide RNG state or a `PYTHONHASHSEED` -- calling this module twice
with the same arguments always yields byte-identical output.

Prompt E addition: every generated `FeatureSet` also carries
`multimodal.features.MULTIMODAL_FEATURE_NAMES` columns (RGB/string-
segmentation/audio), populated by the exact same class-signature-envelope
process as the kinematic columns -- there is no separate "multimodal
synthetic generator". This lets `events.labels.FEATURE_SUBSETS`'s
`"kinematics_only"` and `"multimodal_fused"` entries select different
column subsets of one shared synthetic dataset for the Prompt E ablation
(`events/cli.py`'s `compare-modalities` command), rather than needing two
independently-generated datasets that could drift out of sync.
"""

from __future__ import annotations

import hashlib
import math
import struct
from datetime import UTC, datetime

from yoyovision_ml.dataset.schema import AnnotationProvenance, TrickEventAnnotation
from yoyovision_ml.domain import EventFamily, FeatureFrame, FeatureSet, Outcome, Source
from yoyovision_ml.events.labels import EVENT_CLASSES, OUTCOME_CLASSES
from yoyovision_ml.events.types import TrainingSample
from yoyovision_ml.multimodal.features import MULTIMODAL_FEATURE_NAMES
from yoyovision_ml.perception.features import ALL_FEATURE_NAMES

_SYNTHETIC_TOOL = "yoyovision_ml.events.synthetic"

#: Every synthetic clip carries both the Prompt B kinematic columns and
#: Prompt E's RGB/string-segmentation/audio columns, generated by the exact
#: same class-signature-envelope process (see `_class_signature`) so
#: `events.labels.FEATURE_SUBSETS["kinematics_only"]` and
#: `[...]["multimodal_fused"]` can select sub-tuples of one shared
#: `FeatureSet` rather than needing two separate generators.
_ALL_SYNTHETIC_FEATURE_NAMES: tuple[str, ...] = ALL_FEATURE_NAMES + MULTIMODAL_FEATURE_NAMES


def _stable_seed(*parts: str) -> int:
    digest = hashlib.sha256("|".join(parts).encode("utf-8")).digest()
    return int(struct.unpack(">Q", digest[:8])[0])


def _xorshift_floats(seed: int, count: int) -> list[float]:
    values: list[float] = []
    state = seed or 1
    for _ in range(count):
        state ^= (state << 13) & 0xFFFFFFFFFFFFFFFF
        state ^= state >> 7
        state ^= (state << 17) & 0xFFFFFFFFFFFFFFFF
        values.append((state % 10_000) / 10_000.0)
    return values


def _class_signature(class_idx: int) -> list[float]:
    """A fixed, class-specific "profile" vector over `ALL_FEATURE_NAMES`
    (values in `[-1, 1]`) -- the synthetic clip generator boosts each
    feature column by `profile[i] * envelope(t)` during that class's event
    span, so different classes produce visibly different feature curves for
    the model to actually learn from (rather than pure noise)."""
    raw = _xorshift_floats(
        _stable_seed("class-signature", str(class_idx)), len(_ALL_SYNTHETIC_FEATURE_NAMES)
    )
    return [2.0 * v - 1.0 for v in raw]


_CLASS_SIGNATURES: dict[EventFamily, list[float]] = {
    family: _class_signature(i) for i, family in enumerate(EVENT_CLASSES)
}


def _bell_envelope(t_fraction: float) -> float:
    """Smooth rise-and-fall shape over `t_fraction` in `[0, 1]`, peaking at
    the span's midpoint -- the event "intensifies" then fades, unlike a
    background frame's flat near-zero signal."""
    return math.sin(math.pi * min(1.0, max(0.0, t_fraction)))


def generate_synthetic_sample(
    seed: int,
    video_id: str,
    player_id: str,
    num_events: int = 10,
    fps: float = 30.0,
    gap_ms: int = 300,
    min_event_ms: int = 500,
    max_event_ms: int = 1500,
) -> TrainingSample:
    """Builds one synthetic clip: a `FeatureSet` covering the full clip
    duration plus a matching sequence of non-overlapping `TrickEventAnnotation`s
    (one event per `gap_ms`-separated span), cycling deterministically through
    every Prompt C class and every `OUTCOME_CLASSES` value so a small synthetic
    dataset still has full class/outcome coverage."""
    frame_interval_ms = round(1000.0 / fps)
    trick_events: list[TrickEventAnnotation] = []
    cursor_ms = gap_ms

    for i in range(num_events):
        jitter = _xorshift_floats(_stable_seed("synth-event", video_id, str(i)), 2)
        duration_ms = min_event_ms + int(jitter[0] * (max_event_ms - min_event_ms))
        start_ms = cursor_ms
        end_ms = start_ms + duration_ms
        family = EVENT_CLASSES[(seed + i) % len(EVENT_CLASSES)]
        outcome = Outcome(OUTCOME_CLASSES[(seed + i) % len(OUTCOME_CLASSES)])
        trick_events.append(
            TrickEventAnnotation(
                event_id=f"{video_id}-event-{i}",
                label=f"{family.value}_synthetic",
                family=family,
                start_ms=start_ms,
                end_ms=end_ms,
                outcome=outcome,
                provenance=AnnotationProvenance(
                    annotator_id="synthetic-generator",
                    source=Source.MODEL,
                    annotated_at=datetime(2024, 1, 1, tzinfo=UTC),
                    tool=_SYNTHETIC_TOOL,
                    tool_version="1",
                    is_adjudicated=True,
                    adjudicated_by="synthetic-generator",
                ),
                notes="synthetic: not real footage, generated for pipeline testing only",
            )
        )
        cursor_ms = end_ms + gap_ms

    total_ms = cursor_ms
    n_frames = max(1, int(total_ms / frame_interval_ms))
    frames: list[FeatureFrame] = []
    for frame_idx in range(n_frames):
        frame_ms = frame_idx * frame_interval_ms
        noise = _xorshift_floats(
            _stable_seed("synth-frame", video_id, str(frame_ms)),
            len(_ALL_SYNTHETIC_FEATURE_NAMES),
        )
        values = {
            name: 0.05 * (2.0 * n - 1.0)
            for name, n in zip(_ALL_SYNTHETIC_FEATURE_NAMES, noise, strict=True)
        }

        for event in trick_events:
            if event.start_ms <= frame_ms <= event.end_ms:
                span = max(1, event.end_ms - event.start_ms)
                t_fraction = (frame_ms - event.start_ms) / span
                envelope = _bell_envelope(t_fraction)
                signature = _CLASS_SIGNATURES[event.family]
                for col, name in enumerate(_ALL_SYNTHETIC_FEATURE_NAMES):
                    values[name] += envelope * signature[col]
                break  # events are non-overlapping by construction

        frames.append(FeatureFrame(frame_ms=frame_ms, values=values))

    features = FeatureSet(
        frames=tuple(frames), feature_names=_ALL_SYNTHETIC_FEATURE_NAMES, fps=fps
    )
    return TrainingSample(
        video_id=video_id,
        player_id=player_id,
        features=features,
        trick_events=tuple(trick_events),
    )


def generate_synthetic_dataset(
    num_players: int = 6,
    clips_per_player: int = 2,
    seed: int = 42,
    num_events_per_clip: int = 10,
) -> list[TrainingSample]:
    """Builds a small deterministic multi-player synthetic dataset -- enough
    distinct players for a meaningful player-grouped train/val/test split."""
    samples: list[TrainingSample] = []
    for player_idx in range(num_players):
        player_id = f"synthetic-player-{player_idx:03d}"
        for clip_idx in range(clips_per_player):
            video_id = f"{player_id}-clip-{clip_idx:02d}"
            sample_seed = seed + player_idx * 1000 + clip_idx
            samples.append(
                generate_synthetic_sample(
                    seed=sample_seed,
                    video_id=video_id,
                    player_id=player_id,
                    num_events=num_events_per_clip,
                )
            )
    return samples
